### ISSUE TITLE
CreateFromYaml/CreateFromURI/KoApply needs templating

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/reconciler-test#11]
I like the approach of using yamls, but they need templating features. For example, I could have the same broker config for two different brokers, but i need to change the name of the created resource. For that, we need some basic templating capabilities

**Comment by lionelvillard** [comment]
Yup agree. Rigging supports templating, it just hasn't been integrated properly yet.

I think we also want a leaner interface. Maybe something like this:

```go
type ResourceContext interface {

  Apply(manifest ManifestProvider) 
}
```

More details soon....
