### ISSUE TITLE
Implement Emitter for reporting to json the features result and compliance level

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/reconciler-test#118]
As $title, the emitter can be used to implement the reporting of compliance, e.g. emitting a json for every feature like:

```
{
   "name": "EchoFeature",
   "state": ["Stable"],
   "report": {
     "Alpha": {
       "MUST": ...
     }
   } 
}
```

**Comment by n3wscott** [comment]
I am not sure the report makes the most sense to be ordered by level and state, but I like where this is going.

**Comment by slinkydeveloper** [comment]
@n3wscott The proposed format is absolutely drafted :smile: My point is collecting the things and dump them somewhere for later processing
