### ISSUE TITLE
Define event topology

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/reconciler-test#12]
**WARNING: Brain dump here**

The approach of component seems interesting, although it still doesn't tackle one of the major issues of knative eventing existing e2e tests: deploying components manually, component per component, makes hard understanding the test flow. My idea of an eventing test is something like:

* I tell you what components we have here and how to configure them
* I tell you the topology to chain the components all together
* I stimulate the network with some events
* Asserts

Even using this new framework, the first two bullet points still seems a little bit confused/smashed together, making the whole reasoning about the test complex. I would love to explore the ability to completely separate those two, having some "dsl" or similar to actually tell the tests how to chain the components. For example:

```
sequenceA =>
  serviceA =>
  serviceB =>
  serviceC

brokerA =>
  triggerA =>
    serviceD
  triggerB =>
    sequenceA

ghSource =>
  brokerA

``` 

Or:

```
	GhSource("my-source")
		.ToBroker("broker-a")
		.Trigger("trigger-a",
			Sequence("sequence-a")
				.Service("service-a")
				.Service("service-b")
				.Service("service-c")
		)
		.Trigger("trigger-b",
			Service("service-d")
		)
		.Trigger("trigger-c",
			Sink("sink-a")
		)
```

We can work out on the details of such language/config file, but i wonder if it makes sense to you this approach

**Comment by lionelvillard** [comment]
That's an interesting idea. The current direction is to use YAML specifications to describe such flow but maybe there is a better way. 

Do you think that's something we can add later on or not?

**Comment by slinkydeveloper** [comment]
I don't know _when_ we should add it tbh, but i see the value in it, in particular because it clearly separates the different "phases" of an eventing test. I think we can do it in yaml (if you take the first sample and replace `=>` with `:`, you have a yaml :smile:
