### ISSUE TITLE
Environment.Prerequisite semantics

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/reconciler-test#122]
As $title, how `Environment.Prerequisite` should work? If it fails, should it skip the whole test? Or should it fail it? Do we need to add additional docs about it?

cc @n3wscott

**Comment by n3wscott** [comment]
I think it should fail, it means the test is not runnable. You could choose to `t.Skip()`  in that `Prerequisite` and that would be an opt-in skip, but default if it fails, the test fast fails.

**Comment by slinkydeveloper** [comment]
So, is this correct?

* If prerequisite succeeds, move forward and run all the features
* If prerequisite fails, mark the test as failed (or as skipped?!) and don't run all the features 

I wonder if `Prerequisite` should really accept `Feature` more than `StepFn`... Do we expect `Prerequisite` mutate the cluster state to prepare the features executions? e.g. before running some broker features, should prerequisite create the broker or should each feature create its broker? If yes, what if the prerequisite feature has teardowns too?

Changing to `StepFn` IMO simplify the reason around it: `Prerequisite` then it's just an "assertion" (or more than one) you do on the cluster to check if it makes sense or not to run a set of features, given what's on the cluster

**Comment by mgencur** [comment]
I have to admit that after looking at the API and impl of the `Prerequisite` function it's still a little confusing:
From the interface it looks like they're doing completely the same:
```
        // Prerequisite will execute the feature using the given Context and T,
	// the feature should not have any asserts.
	Prerequisite(ctx context.Context, t *testing.T, f *feature.Feature)

	// Test will execute the feature test using the given Context and T.
	Test(ctx context.Context, t *testing.T, f *feature.Feature)
```
And the implementation of Prerequisite actually just calls the `Test` implementation directly, just giving the test a different name "Prerequisite".
If I understand it correctly the Prerequisite should mutate the environment in the way that is common to all the features that will be executed later. If this is true then perhaps it would help changing the last argument from Feature to StepFn. Or rename the function to `Configure` or `Amend` ?
