### ISSUE TITLE
Eventshub should support sending malformed events.

### ISSUE THREAD

**Issue by vaikas** [knative-sandbox/reconciler-test#146]
Discovered in:
https://github.com/knative/eventing/pull/5101

I was wanting to use eventshub to send the event, and in particular send a version of cloudevents that was not 0.3 or 1.0 but this was impossible.

So either, we need to have a way to send malformed events to test failures, or we need to have another tool (not desirable) to do this.

Also, it should be easier to find a way to do POST vs. GET and get the response in an easier way than currently. We can maybe do this already, but it's not very easy, nor is it easy to figure out which sent event goes with what response.

@slinkydeveloper

**Comment by slinkydeveloper** [comment]
You cannot send malformed events, but more than sending events you can just manually set headers and payload:

* https://github.com/knative-sandbox/reconciler-test/blob/main/pkg/eventshub/options.go#L151
* https://github.com/knative-sandbox/reconciler-test/blob/main/pkg/eventshub/options.go#L156

With https://github.com/knative-sandbox/reconciler-test/pull/141, you can also specify the http method to use
