### ISSUE TITLE
Resources installed outside of the test namespace are not deleted

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/reconciler-test#167]

**Comment by vaikas** [comment]
If you create them in the Feature, this should probably give you access to it. Is that enough?
https://github.com/knative-sandbox/reconciler-test/blob/main/pkg/feature/feature.go#L102

And then you can use it like this:
https://github.com/knative-sandbox/reconciler-test/pull/185

Or if you need more control:
https://github.com/knative/eventing/blob/main/test/rekt/features/broker/control_plane.go#L582

Is that giving you what you need?
