### ISSUE TITLE
Make cleanups easier and just use k8s ownerrefs for it.

### ISSUE THREAD

**Issue by vaikas** [knative-sandbox/reconciler-test#184]
One possibly terrible idea that I floated by @n3wscott was that in our Install phases, since we see all the resources created, we could create a 'dummy' resource, say configmap that contains deets about the particular Feature that's currently being tested. So, if we were to do that, then in the Install, we could set the OwnerRef to point to that configmap and in the cleanup phase (could make it so it only happens in the success for example, etc.) we just have to delete the ConfigMap and we can utilize k8s garbage collection to do the cleanups for us and we wouldn't have to do quite as much manual cleanup. 

This would be a followup to:
https://github.com/knative-sandbox/reconciler-test/pull/183

**Comment by lionelvillard** [comment]
Keep in mind that ownerrefs don't work across namespaces, so you need one configmap per namespace. How do you cleanup the namespace itself?

**Comment by vaikas** [comment]
It's one cm per feature and each feature is in a given namespace. At least that's what I was thinking.
