### ISSUE TITLE
Proposal: change the responce code in eventshub receiver for dropped events

### ISSUE THREAD

**Issue by xinydev** [knative-sandbox/reconciler-test#211]
I am writing an e2e test for apiServerSource's retry feature, but the `cloudevents.Client` only retries when the HTTP response code is one of  [these](https://github.com/cloudevents/sdk-go/blob/main/v2/protocol/http/protocol.go#L40).   

I want to use eventshub to simulate a events lost scenario but the eventshub returns [http.StatusConflict](https://github.com/knative-sandbox/reconciler-test/blob/main/pkg/eventshub/receiver/receiver.go#L214) when dropping events. and the `http.StatusConflict` is not one of the codes which `cloudevents.Client` retries.  

So I have a question. Is there any special reason to choose  `http.StatusConflict` ? 

Can we change it to `429(Too Many Requests)` or `503(Service Unavailable)` or `504(Gateway Timeout)` for some tests scenario like retring?  

Or is there any advices for this e2e test?

**Comment by xinydev** [comment]
@vaikas What do you think of this

**Comment by vaikas** [comment]
Not totally sure if this would fit your use case, but for RabbitMQ Broker, I ended up using this:
https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/pkg/dispatcher/dispatcher.go#L80

With some more context here:
https://github.com/cloudevents/sdk-go/pull/596

**Comment by xinydev** [comment]
> Not totally sure if this would fit your use case, but for RabbitMQ Broker, I ended up using this:
> https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/pkg/dispatcher/dispatcher.go#L80
> 
> With some more context here:
> [cloudevents/sdk-go#596](https://github.com/cloudevents/sdk-go/pull/596)

Thanks!  It is very helpful!

**Comment by vaikas** [comment]
Great to hear :) Ping me if you need some more help :)

**Comment by xinydev** [comment]
@vaikas  Hi, what do you think we add a new env `DropEventsResponseCode` to config the status code returned when dropping events ?    

I think in my scenario(https://github.com/knative/eventing/pull/5457), it might not be good to modify the default strategy of [cloudevent.Client](https://github.com/knative/eventing/blob/fa6b0b08a5c1e2542fba50c35d82df9baff2cc56/pkg/adapter/v2/cloudevents.go#L47) 
in pkg/adapter for the convenience of writing tests, because It may affect other components that use cloudevent.Client.

**Comment by pierDipi** [comment]
@xinydev makes sense to me, and it will be a lot useful for testing the behavior of some specific status codes.
