### ISSUE TITLE
Can step fn panic? is the panic recovered and recorded as failure?

### ISSUE THREAD

**Issue by n3wscott** [knative-sandbox/reconciler-test#32]
Can step fn panic? is the panic recovered and recorded as failure?

_Originally posted by @slinkydeveloper in https://github.com/knative-sandbox/reconciler-test/pull/30#discussion_r520365372_

**Comment by slinkydeveloper** [comment]
We might still need to take some actions about this, I'll analyze where we're at and eventually push a PR to fill the gap.

/assign
