### ISSUE TITLE
Failing tests leaves namespace up 

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/reconciler-test#40]
This may be useful for debugging, but I guess it should be opt-in and by default the framework should just cleanup the namespace from the cluster

**Comment by tayarani** [comment]
It's not just failing tests. Even successful runs leave the ns around.

**Comment by slinkydeveloper** [comment]
@n3wscott how about when configuring the environment with `globalEnv.Environment` we pass `testing.T`? So then we can hook the finish to the test lifecycle:

```
globalEnvironment.Environment(t, ....)
``` 

Inside `Environment`:

```
t.Cleanup(this.Finish)
```

**Comment by n3wscott** [comment]
we can add a flag in env to keep namespaces around on finish.
