### ISSUE TITLE
Support k8s.IsReady for non-standard resources.

### ISSUE THREAD

**Issue by n3wscott** [knative-sandbox/reconciler-test#58]
this is neat, for the Rabbit cluster operator, I needed to spin through all the conditions since they didn't have a top level condition. It might be useful to have another variant of this (or not) that says, if all the conditions are ready, or be able to pass an array of conditions that must be ready for the resource to be ready. obvs, followup if ever.

_Originally posted by @vaikas in https://github.com/knative-sandbox/reconciler-test/pull/57#discussion_r528990486_

**Comment by n3wscott** [comment]
We could do this by looking if it has a `Ready` condition use that, if not, look for `Succeeded`. If not then maybe we look at the sum of all the rest...?

**Comment by vaikas** [comment]
yeah, sumtin like that.
