### ISSUE TITLE
Eventshub should allow the sender to take in a gvr of an addressable

### ISSUE THREAD

**Issue by n3wscott** [knative-sandbox/reconciler-test#63]
Ideal solution: let the source have an option to be configured with K_SINK and SinkBinding.

This is true for cases where the sink is not known or addressable at the time of eventshub source creation.

**Comment by slinkydeveloper** [comment]
This is already implemented https://github.com/knative-sandbox/reconciler-test/blob/main/pkg/eventshub/options.go#L53
