### ISSUE TITLE
Framework should report Prerequisite features with Asserts

### ISSUE THREAD

**Issue by n3wscott** [knative-sandbox/reconciler-test#64]
We should have a strict mode that fails or normal mode that warns when the feature passed to`env.Prerequisite(...)` has leveled assertions, it can cause issues when running filtered test runs. 

The test author should be able to opt into this behaviour if that is what they want to be doing.

Needs more discussion.

**Comment by slinkydeveloper** [comment]
@n3wscott is this already implemented by #119/#112?
